#!/bin/sh

branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

function fetch_upstream() {
  echo "fetching from upstream..."
  git fetch upstream
}

function checkout_staging() {
  echo "checking out staging branch"
  git checkout staging
}

function merge_upstream() {
  echo "merging from upstream"
  git merge upstream/staging
}

function check_upstream_exists() {
  echo "checking to see if upstream exists"
  if git config remote.upstream.url > /dev/null;  then
    echo "upstream exists...syncing now"
  else
    echo "adding upstream to your remotes"
    git remote add upstream https://github.com/revaturelabs/assignforce-client.git
  fi
}

function stash() {
  echo "stashing uncommitted changes"
  git stash
}

function unstash() {
  echo "retrieving stashed changes"
  git stash pop
}

function checkout_branch() {
  echo "switching to $branch branch"
  git checkout ${branch}
}

function sync() {
  echo "syncing upstream with origin"
  fetch_upstream
  checkout_staging
  merge_upstream
}

function push_to_fork() {
  echo "pushing changes to origin on GitHub"
  git commit -am "sync with upstream"
}

function merge() {
  echo "merging origin/staging with $branch"
  git merge staging
}

option="${1}"
case ${option} in
  "init")
    check_upstream_exists
    stash
    sync
    checkout_branch
    unstash
    ;;
  "sync")
    stash
    sync
    checkout_branch
    unstash
    ;;
  "merge")
    stash
    sync
    push_to_fork
    checkout_branch
    merge
    unstash
    ;;
  *)
    echo "Invalid command...Options:"
    echo "--------------------------"
    echo "sh fsync init    --> initialize upstream and sync"
    echo "sh fsync sync    --> sync with upstream"
    echo "sh fsync merge   --> sync with upstream, push and merge with current branch (use with caution)"
    ;;
esac

